
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Namordnick
{

using System;
    using System.Collections.Generic;
    
public partial class basket
{

    public int id { get; set; }

    public Nullable<int> bookId { get; set; }



    public virtual books books { get; set; }

}

}
